on:
  workflow_dispatch:
  schedule:
    - cron: '0 1 * * *'

name: Mirror GitHub Selected Repos to Gitee
jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source codes
        uses: actions/checkout@v2
      - name: Mirror Github to Gitee with white list
        uses: caoximu/hub-mirror-action@master
        with:
          src: github/caoximu
          dst: gitee/Fewom
          dst_key: ${{ ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCbWo7hgejI1DE2LsxFF12zEOsBcIZKGCJiypkncr9CCtQ++0hu3T4IJPgmBZuxty3tdicpHRBs6r1CIyEJWIyfoxK9PDHxaJHX1tj7Xo3D+5eTp5xKHwaK90SsMOZ2R2vTC1JWqcPSu/zv3BXLjeBEpTfaf3BzBDWNdocYpMqnxlNHpwx5qEiyjV9BKAWZnOdUjrlLNHjg2HT6/sXSTTWzxkkFSz+wQ2RRo8IbAqa+yNaNeQz8rCUatuzQ29LuZl3yMWlZy3tVMoRZ4c/NhmSwzaG993eKKCa6I6eYBGRB5S3KY+fP/x/M1CoO74gTiIHbTrOPsCUtsAR00tSgL6dMZAnLl7i1T6VgtW1z1Qe85fcgXeJ2+gx+ixNJEtd386Ne9Y06qdb0BPr1S6zQsxABtQXCSuwx3BCwM19+2fKB1PM7n/1IhSbFLekxvsO/RMwLUN06w64Ig7NaPbYQuGGtPa0cUpo0Ps03TdwUMIawcPs2U+oaFo+QMqnxZWX0jIc= caoximu55@gmail.com}}
          dst_token:  ${{ bad483ff74065c5e1542f8b6823aa767 }}
          force_update: true
